services:
  frontend:
    build: .
    image: dad-frontend
    container_name: dad-frontend
    ports:
      - "5173:80"
    restart: unless-stopped
    networks:
      - sail

networks:
  sail:
    external: true
    name: api_sail
